CREATE TABLE bid
(
    id                    UUID         NOT NULL,
    producer_id           UUID         NOT NULL,
    lot_id                UUID         NOT NULL,
    billing_type          VARCHAR(255) NOT NULL,
    bid_price             DECIMAL      NOT NULL,
    state                 VARCHAR(255) NOT NULL,
    creation_date_time    TIMESTAMP WITHOUT TIME ZONE,
    last_update_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bid PRIMARY KEY (id)
);

CREATE TABLE lot
(
    id                    UUID         NOT NULL,
    lot_order             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    state                 VARCHAR(255),
    claim_id              UUID         NOT NULL,
    customer_id           UUID         NOT NULL,
    confirmed_bid_id      UUID,
    delivery_date         date         NOT NULL,
    arrive_date           date         NOT NULL,
    delivery_address      VARCHAR(255) NOT NULL,
    arrive_address        VARCHAR(255) NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    weight                INTEGER      NOT NULL,
    hazard                VARCHAR(255),
    place_for_cargo       SMALLINT     NOT NULL,
    size                  SMALLINT     NOT NULL,
    temperature_from      SMALLINT,
    temperature_to        SMALLINT,
    vehicle_type          VARCHAR(255) NOT NULL,
    vehicle_sub_type      VARCHAR(255) NOT NULL,
    delivery_placing_type VARCHAR(255),
    arrive_placing_type   VARCHAR(255),
    amount                SMALLINT     NOT NULL,
    budget                DECIMAL,
    billing_type          VARCHAR(255),
    creation_date_time    TIMESTAMP WITHOUT TIME ZONE,
    last_update_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lot PRIMARY KEY (id)
);

ALTER TABLE lot
    ADD CONSTRAINT uc_lot_claimid UNIQUE (claim_id);

ALTER TABLE lot
    ADD CONSTRAINT uc_lot_lotorder UNIQUE (lot_order);

CREATE TABLE claim
(
    id                    UUID         NOT NULL,
    claim_order           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id           UUID         NOT NULL,
    state                 VARCHAR(255) NOT NULL,
    creation_date_time    TIMESTAMP WITHOUT TIME ZONE,
    last_update_date_time TIMESTAMP WITHOUT TIME ZONE,
    delivery_date         date         NOT NULL,
    arrive_date           date         NOT NULL,
    delivery_address      VARCHAR(255) NOT NULL,
    arrive_address        VARCHAR(255) NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    weight                INTEGER      NOT NULL,
    place_for_cargo       SMALLINT     NOT NULL,
    size                  SMALLINT     NOT NULL,
    hazard                VARCHAR(255),
    temperature_from      SMALLINT,
    temperature_to        SMALLINT,
    vehicle_type          VARCHAR(255) NOT NULL,
    vehicle_sub_type      VARCHAR(255) NOT NULL,
    delivery_placing_type VARCHAR(255) NOT NULL,
    arrive_placing_type   VARCHAR(255),
    amount                SMALLINT     NOT NULL,
    budget                DECIMAL,
    billing_type          VARCHAR(255),
    CONSTRAINT pk_claim PRIMARY KEY (id)
);

ALTER TABLE claim
    ADD CONSTRAINT uc_claim_claimorder UNIQUE (claim_order);

CREATE TABLE organization
(
    id                    UUID                        NOT NULL,
    inn                   BIGINT                      NOT NULL,
    kpp                   BIGINT,
    organization_name     VARCHAR(255)                NOT NULL,
    short_name            VARCHAR(255)                NOT NULL,
    actuality_date        date                        NOT NULL,
    registration_date     date                        NOT NULL,
    okved                 VARCHAR(255)                NOT NULL,
    okved_type            VARCHAR(255)                NOT NULL,
    address               VARCHAR(255)                NOT NULL,
    type                  VARCHAR(255)                NOT NULL,
    branch_type           VARCHAR(255),
    branch_count          INTEGER,
    status                VARCHAR(255)                NOT NULL,
    create_date_time      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_update_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    management_full_name  VARCHAR(255)                NOT NULL,
    post                  VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

CREATE TABLE globus_user
(
    id                     UUID         NOT NULL,
    role                   VARCHAR(255) NOT NULL,
    organization_id        UUID,
    state                  VARCHAR(255) NOT NULL,
    registration_date_time TIMESTAMP WITHOUT TIME ZONE,
    last_update_date_time  TIMESTAMP WITHOUT TIME ZONE,
    first_name             VARCHAR(255) NOT NULL,
    last_name              VARCHAR(255) NOT NULL,
    middle_name            VARCHAR(255),
    phone                  VARCHAR(255) NOT NULL,
    email                  VARCHAR(255) NOT NULL,
    birth_day              date,
    is_paid                BOOLEAN,
    finish_date            date,
    plan                   VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE globus_user
    ADD CONSTRAINT FK_USER_ON_ORGANIZATION_IS FOREIGN KEY (organization_id) REFERENCES organization (id);

CREATE TABLE telegram_user
(
    telegram_user_id BIGINT NOT NULL,
    chat_id          BIGINT NOT NULL,
    user_id          UUID   NOT NULL,
    CONSTRAINT pk_telegramuser PRIMARY KEY (telegram_user_id)
);

ALTER TABLE telegram_user
    ADD CONSTRAINT uc_telegramuser_chatid UNIQUE (chat_id);

ALTER TABLE telegram_user
    ADD CONSTRAINT uc_telegramuser_userid UNIQUE (user_id);